package com.mraulio.gbcameramanager.utils;

import java.util.HashMap;
import java.util.Map;

/**
 * Based on this https://github.com/HerrZatacke/gb-printer-web/blob/master/src/javascript/tools/transformSav/charMap.js
 */
public class CharMap {

    public static final Map<Integer, String> CHAR_MAP_INT = new HashMap<Integer, String>() {{
        put(0x56, "A");
        put(0x57, "B");
        put(0x58, "C");
        put(0x59, "D");
        put(0x5A, "E");
        put(0x5B, "F");
        put(0x5C, "G");
        put(0x5D, "H");
        put(0x5E, "I");
        put(0x5F, "J");
        put(0x60, "K");
        put(0x61, "L");
        put(0x62, "M");
        put(0x63, "N");
        put(0x64, "O");
        put(0x65, "P");
        put(0x66, "Q");
        put(0x67, "R");
        put(0x68, "S");
        put(0x69, "T");
        put(0x6A, "U");
        put(0x6B, "V");
        put(0x6C, "W");
        put(0x6D, "X");
        put(0x6E, "Y");
        put(0x6F, "Z");
        put(0x70, "_");
        put(0x71, "\'");
        put(0x72, ",");
        put(0x73, ".");
        put(0x74, "Á");
        put(0x75, "Â");
        put(0x76, "À");
        put(0x77, "Ä");
        put(0x78, "É");
        put(0x79, "Ê");
        put(0x7A, "È");
        put(0x7B, "Ë");
        put(0x7C, "Í");
        put(0x7D, "Ï");
        put(0x7E, "Ó");
        put(0x7F, "Ö");
        put(0x80, "Ú");
        put(0x81, "Ü");
        put(0x82, "Ñ");
        put(0x83, "-");
        put(0x84, "&");
        put(0x85, "!");
        put(0x86, "?");
        put(0x87, " ");
        put(0x88, "a");
        put(0x89, "b");
        put(0x8A, "c");
        put(0x8B, "d");
        put(0x8C, "e");
        put(0x8D, "f");
        put(0x8E, "g");
        put(0x8F, "h");
        put(0x90, "i");
        put(0x91, "j");
        put(0x92, "k");
        put(0x93, "l");
        put(0x94, "m");
        put(0x95, "n");
        put(0x96, "o");
        put(0x97, "p");
        put(0x98, "q");
        put(0x99, "r");
        put(0x9A, "s");
        put(0x9B, "t");
        put(0x9C, "u");
        put(0x9D, "v");
        put(0x9E, "w");
        put(0x9F, "x");
        put(0xA0, "y");
        put(0xA1, "z");
        put(0xA2, "•");
        put(0xA3, "~");
        put(0xA4, "📱");
        put(0xA5, " ");
        put(0xA6, "á");
        put(0xA7, "â");
        put(0xA8, "à");
        put(0xA9, "ä");
        put(0xAA, "é");
        put(0xAB, "ê");
        put(0xAC, "è");
        put(0xAD, "ë");
        put(0xAE, "í");
        put(0xAF, "ï");
        put(0xB0, "ó");
        put(0xB1, "ö");
        put(0xB2, "ú");
        put(0xB3, "ü");
        put(0xB4, "ñ");
        put(0xB5, "ḉ");
        put(0xB6, "ß");
        put(0xB7, "😄");
        put(0xB8, "😟");
        put(0xB9, "😅");
        put(0xBA, "0");
        put(0xBB, "1");
        put(0xBC, "2");
        put(0xBD, "3");
        put(0xBE, "4");
        put(0xBF, "5");
        put(0xC0, "6");
        put(0xC1, "7");
        put(0xC2, "8");
        put(0xC3, "9");
        put(0xC4, "/");
        put(0xC5, ":");
        put(0xC6, "~");
        put(0xC7, "\"");
        put(0xC8, "@");
    }};

    public static final Map<Integer, String> CHAR_MAP_JP = new HashMap<Integer, String>() {{
        put(0x01, "あ");
        put(0x02, "い");
        put(0x03, "う");
        put(0x04, "え");
        put(0x05, "お");
        put(0x06, "か");
        put(0x07, "き");
        put(0x08, "く");
        put(0x09, "け");
        put(0x0a, "こ");

        put(0x0b, "さ");
        put(0x0c, "し");
        put(0x0d, "す");
        put(0x0e, "せ");
        put(0x0f, "そ");
        put(0x10, "た");
        put(0x11, "ち");
        put(0x12, "つ");
        put(0x13, "て");
        put(0x14, "と");

        put(0x15, "な");
        put(0x16, "に");
        put(0x17, "ぬ");
        put(0x18, "ね");
        put(0x19, "の");
        put(0x1a, "は");
        put(0x1b, "ひ");
        put(0x1c, "ふ");
        put(0x1d, "へ");
        put(0x1e, "ほ");

        put(0x1f, "ま");
        put(0x20, "み");
        put(0x21, "む");
        put(0x22, "め");
        put(0x23, "も");
        put(0x24, "や");
        put(0x25, "ゆ");
        put(0x26, "よ");
        put(0x27, "、");
        put(0x28, "。");

        put(0x29, "ら");
        put(0x2a, "り");
        put(0x2b, "る");
        put(0x2c, "れ");
        put(0x2d, "ろ");
        put(0x2e, "わ");
        put(0x2f, "を");
        put(0x30, "ん");
        put(0x31, "〜");
        put(0x32, "♥");

        put(0x33, "が");
        put(0x34, "ぎ");
        put(0x35, "ぐ");
        put(0x36, "げ");
        put(0x37, "ご");
        put(0x38, "ざ");
        put(0x39, "じ");
        put(0x3a, "ず");
        put(0x3b, "ぜ");
        put(0x3c, "ぞ");

        put(0x3d, "だ");
        put(0x3e, "ぢ");
        put(0x3f, "づ");
        put(0x40, "で");
        put(0x41, "ど");
        put(0x42, "ば");
        put(0x43, "び");
        put(0x44, "ぶ");
        put(0x45, "べ");
        put(0x46, "ぼ");

        put(0x47, "ぱ");
        put(0x48, "ぴ");
        put(0x49, "ぷ");
        put(0x4a, "ぺ");
        put(0x4b, "ぽ");
        put(0x4c, "っ");
        put(0x4d, "ゃ");
        put(0x4e, "ゅ");
        put(0x4f, "ょ");
        put(0x50, "・");

        put(0x51, "ぁ");
        put(0x52, "ぃ");
        put(0x53, "ぅ");
        put(0x54, "ぇ");
        put(0x55, "ぉ");
        put(0x56, "ア");
        put(0x57, "イ");
        put(0x58, "ウ");
        put(0x59, "エ");
        put(0x5a, "オ");

        put(0x5b, "カ");
        put(0x5c, "キ");
        put(0x5d, "ク");
        put(0x5e, "ケ");
        put(0x5f, "コ");
        put(0x60, "サ");
        put(0x61, "シ");
        put(0x62, "ス");
        put(0x63, "セ");
        put(0x64, "ソ");

        put(0x65, "タ");
        put(0x66, "チ");
        put(0x67, "ツ");
        put(0x68, "テ");
        put(0x69, "ト");
        put(0x6a, "ナ");
        put(0x6b, "ニ");
        put(0x6c, "ヌ");
        put(0x6d, "ネ");
        put(0x6e, "ノ");

        put(0x6f, "ハ");
        put(0x70, "ヒ");
        put(0x71, "フ");
        put(0x72, "ヘ");
        put(0x73, "ホ");
        put(0x74, "マ");
        put(0x75, "ミ");
        put(0x76, "ム");
        put(0x77, "メ");
        put(0x78, "モ");

        put(0x79, "ヤ");
        put(0x7a, "ユ");
        put(0x7b, "ヨ");
        put(0x7c, "!");
        put(0x7d, "?");
        put(0x7e, "ラ");
        put(0x7f, "リ");
        put(0x80, "ル");
        put(0x81, "レ");
        put(0x82, "ロ");

        put(0x83, "ワ");
        put(0x84, "ヲ");
        put(0x85, "ン");
        put(0x86, "ヴ");
        put(0x87, " ");
        put(0x88, "ガ");
        put(0x89, "ギ");
        put(0x8a, "グ");
        put(0x8b, "ゲ");
        put(0x8c, "ゴ");

        put(0x8d, "ザ");
        put(0x8e, "ジ");
        put(0x8f, "ズ");
        put(0x90, "ゼ");
        put(0x91, "ゾ");
        put(0x92, "ダ");
        put(0x93, "ヂ");
        put(0x94, "ヅ");
        put(0x95, "デ");
        put(0x96, "ド");

        put(0x97, "バ");
        put(0x98, "ビ");
        put(0x99, "ブ");
        put(0x9a, "ベ");
        put(0x9b, "ボ");
        put(0x9c, "パ");
        put(0x9d, "ピ");
        put(0x9e, "プ");
        put(0x9f, "ペ");
        put(0xa0, "ポ");

        put(0xa1, "ッ");
        put(0xa2, "ャ");
        put(0xa3, "ュ");
        put(0xa4, "ョ");
        put(0xa5, "ー");
        put(0xa6, "ァ");
        put(0xa7, "ィ");
        put(0xa8, "ゥ");
        put(0xa9, "ェ");
        put(0xaa, "ォ");

        put(0xab, "A");
        put(0xac, "B");
        put(0xad, "C");
        put(0xae, "D");
        put(0xaf, "E");
        put(0xb0, "F");
        put(0xb1, "G");
        put(0xb2, "H");
        put(0xb3, "I");
        put(0xb4, "J");
        put(0xb5, "K");
        put(0xb6, "L");
        put(0xb7, "M");
        put(0xb8, "N");
        put(0xb9, "O");
        put(0xba, "P");
        put(0xbb, "Q");
        put(0xbc, "R");
        put(0xbd, "S");
        put(0xbe, "T");
        put(0xbf, "U");
        put(0xc0, "V");
        put(0xc1, "W");
        put(0xc2, "X");
        put(0xc3, "Y");
        put(0xc4, "Z");
        put(0xc5, "_");
        put(0xc6, "'");
        put(0xc7, ",");
        put(0xc8, ".");
        put(0xc9, "a");
        put(0xca, "b");
        put(0xcb, "c");
        put(0xcc, "d");
        put(0xcd, "e");
        put(0xce, "f");
        put(0xcf, "g");
        put(0xd0, "h");
        put(0xd1, "i");
        put(0xd2, "j");
        put(0xd3, "k");
        put(0xd4, "l");
        put(0xd5, "m");
        put(0xd6, "n");
        put(0xd7, "o");
        put(0xd8, "p");
        put(0xd9, "q");
        put(0xda, "r");
        put(0xdb, "s");
        put(0xdc, "t");
        put(0xdd, "u");
        put(0xde, "v");
        put(0xdf, "w");
        put(0xe0, "x");
        put(0xe1, "y");
        put(0xe2, "z");
        put(0xe3, "📱");
        put(0xe4, "😅");
        put(0xe5, "😄");
        put(0xe6, "_");
        put(0xe7, "0");
        put(0xe8, "1");
        put(0xe9, "2");
        put(0xea, "3");
        put(0xeb, "4");
        put(0xec, "5");
        put(0xed, "6");
        put(0xee, "7");
        put(0xef, "8");
        put(0xf0, "9");
        put(0xf1, "/");
        put(0xf2, ":");
        put(0xf3, "~");
        put(0xf4, "\"");
        put(0xf5, "@");

    }};

    public static final String charMapDateDigit = "00123456789?????";
}
